services:

  postgres:
    image: postgres:17.2-alpine
    container_name: snx_bot_postgres
    volumes:
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SYNTHETIX_DB_PASSWORD: ${SYNTHETIX_DB_PASSWORD}

  app:
    build: .
    container_name: snx_staking_tg_bot
    depends_on:
      - postgres
    environment:
      - ALCHEMY_KEY=${ALCHEMY_KEY}
      - ETHERSCAN_KEY=${ETHERSCAN_KEY}
      - ETHEREUM_ISSUANCE_RATIO=${ETHEREUM_ISSUANCE_RATIO}
      - OPTIMISM_ISSUANCE_RATIO=${OPTIMISM_ISSUANCE_RATIO}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - ETHEREUM_ADDRESS_RESOLVER_ADDRESS=${ETHEREUM_ADDRESS_RESOLVER_ADDRESS}
      - OPTIMISM_ADDRESS_RESOLVER_ADDRESS=${OPTIMISM_ADDRESS_RESOLVER_ADDRESS}
      - DB_CONNECTION=${DB_CONNECTION}
    restart: unless-stopped