"""init

Revision ID: 3daa2073abb5
Revises: 
Create Date: 2025-02-21 14:10:59.978118

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3daa2073abb5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chain', sa.Enum('optimism', 'ethereum', name='chain'), nullable=False),
    sa.Column('c_ratio', sa.Float(), server_default='0', nullable=False),
    sa.Column('snx_count', sa.Numeric(precision=50, scale=0), server_default='0', nullable=False),
    sa.Column('collateral', sa.Numeric(precision=50, scale=0), server_default='0', nullable=False),
    sa.Column('sds_count', sa.Numeric(precision=50, scale=0), server_default='0', nullable=False),
    sa.Column('debt', sa.Numeric(precision=50, scale=0), server_default='0', nullable=False),
    sa.Column('claimable_snx', sa.Numeric(precision=50, scale=0), server_default='0', nullable=False),
    sa.Column('liquidation_deadline', sa.DateTime(), nullable=True),
    sa.Column('inited', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_address'), 'account', ['address'], unique=False)
    op.create_index(op.f('ix_account_id'), 'account', ['id'], unique=True)
    op.create_table('chat',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dashboard_message_id', sa.Integer(), nullable=True),
    sa.Column('sent_notif_message_id', sa.Integer(), nullable=True),
    sa.Column('sent_notif_message_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_id'), 'chat', ['id'], unique=False)
    op.create_table('chataccount',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('account_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chataccount_id'), 'chataccount', ['id'], unique=True)
    op.create_table('notif',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('type', sa.Enum('ratio', 'rewards_claimable', 'rewards_claimed', 'flagged_for_liquidation', name='notiftype'), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('chat_account_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['chat_account_id'], ['chataccount.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notif_id'), 'notif', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notif_id'), table_name='notif')
    op.drop_table('notif')
    op.drop_index(op.f('ix_chataccount_id'), table_name='chataccount')
    op.drop_table('chataccount')
    op.drop_index(op.f('ix_chat_id'), table_name='chat')
    op.drop_table('chat')
    op.drop_index(op.f('ix_account_id'), table_name='account')
    op.drop_index(op.f('ix_account_address'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
