proxy_abi = [
    {
        "inputs": [{"internalType": "address", "name": "_owner", "type": "address"}],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "constructor",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": False, "internalType": "address", "name": "oldOwner", "type": "address"},
            {"indexed": False, "internalType": "address", "name": "newOwner", "type": "address"},
        ],
        "name": "OwnerChanged",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": False, "internalType": "address", "name": "newOwner", "type": "address"}
        ],
        "name": "OwnerNominated",
        "type": "event",
    },
    {
        "anonymous": False,
        "inputs": [
            {
                "indexed": False,
                "internalType": "contract Proxyable",
                "name": "newTarget",
                "type": "address",
            }
        ],
        "name": "TargetUpdated",
        "type": "event",
    },
    {"payable": True, "stateMutability": "payable", "type": "fallback"},
    {
        "constant": False,
        "inputs": [
            {"internalType": "bytes", "name": "callData", "type": "bytes"},
            {"internalType": "uint256", "name": "numTopics", "type": "uint256"},
            {"internalType": "bytes32", "name": "topic1", "type": "bytes32"},
            {"internalType": "bytes32", "name": "topic2", "type": "bytes32"},
            {"internalType": "bytes32", "name": "topic3", "type": "bytes32"},
            {"internalType": "bytes32", "name": "topic4", "type": "bytes32"},
        ],
        "name": "_emit",
        "outputs": [],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [],
        "name": "acceptOwnership",
        "outputs": [],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [{"internalType": "address", "name": "_owner", "type": "address"}],
        "name": "nominateNewOwner",
        "outputs": [],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "nominatedOwner",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "owner",
        "outputs": [{"internalType": "address", "name": "", "type": "address"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
    {
        "constant": False,
        "inputs": [{"internalType": "contract Proxyable", "name": "_target", "type": "address"}],
        "name": "setTarget",
        "outputs": [],
        "payable": False,
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "constant": True,
        "inputs": [],
        "name": "target",
        "outputs": [{"internalType": "contract Proxyable", "name": "", "type": "address"}],
        "payable": False,
        "stateMutability": "view",
        "type": "function",
    },
]
